version: '3.1'

services:
    server:
        build: .
        container_name: server
        command: sh -c 'python manage.py migrate && python manage.py makemigrations && python manage.py runserver ${server_HostPort}'
        volumes:
            - .:/app
        ports:
            - 8900:8900
        environment:
            - DATABASE_HOST=db
        links:
            - db
        depends_on:
            db:
                condition: service_healthy
    db:
        image: mysql:8.0
        restart: always
        container_name: db
        ports:
            - 3307:3306
        env_file:
            - .env
        volumes:
            - ./db_data:/var/lib/mysql
            - ./Poems.sql:/docker-entrypoint-initdb.d/Poems.sql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 5s
            timeout: 3s
            retries: 5

volumes:
    db_data:
        name: db_data
