# Generated by Django 4.2.7 on 2023-11-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Text of the fortune cookie', max_length=350, verbose_name='Text of the fortune cookie')),
            ],
        ),
    ]
