# Generated by Django 4.2.7 on 2023-11-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRFAPI_test__main', '0003_alter_theme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.CharField(choices=[('About Daytime', 'Abount Daytime'), ('About Countries and towns', 'About Countries and towns'), ('About Seasons', 'About Seasons'), ('About Hollydays', 'About Holidays'), ('About Nature', 'About Nature')], help_text='Theme of the Poem', max_length=100, verbose_name='Theme of the Poem'),
        ),
    ]
