# Generated by Django 4.2.7 on 2023-11-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRFAPI_test__main', '0005_alter_theme_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='text',
            field=models.TextField(default=1, help_text='Text of the Poem', max_length=5000, verbose_name='Text of the Poem'),
            preserve_default=False,
        ),
    ]
